### ISSUE TITLE
how to install rpcddsgen tool ?

### ISSUE THREAD

**Issue by ding511265378** [eProsima/RPC#12]
I have downloaded the installation package according to the tutorial on the official website. Both Linux and windows have tried and failed. I thought the reason is probably due to rpcddsgen.jar error.
Please give the detailed installation tutorial and installation package, looking forward to your reply.

**Comment by richiware** [comment]
Which packages did you downloaded? From https://www.eprosima.com? Could you paste the errors you had?

**Comment by hero952** [comment]
hello:

1. env:
java -version
  java version "1.8.0_321"
 Java(TM) SE Runtime Environment (build 1.8.0_321-b07)
 Java HotSpot(TM) 64-Bit Server VM (build 25.321-b07, mixed mode)

gradle -v
   Gradle 4.4.1

2. Steps：
   $ mkdir ~/RPC
   $ cd RPC
   $ git clone https://github.com/eProsima/RPC.git     
        master branch
   $ cd ~/RPC/RPC/fastrpcgen
   $ gradle assemble
**
ANTXR Parser Generator   Version 0.9.0   Copyright (c) 2005, Scott Stanchfield, JavaDude.com
:buildIDLParser
:idl:clean
:idl:antlr4 UP-TO-DATE
:idl:compileJava
:idl:processResources
:idl:classes
:idl:jar
:idl:assemble
:idl:compileTestJava NO-SOURCE
:idl:processTestResources NO-SOURCE
:idl:testClasses UP-TO-DATE
:idl:test NO-SOURCE
:idl:check UP-TO-DATE
:idl:build
:compileJava/home/zhito/RPC/RPC/fastrpcgen/build/generated-src/com/eprosima/fastrpc/wadl/grammar/WADLParser.java:42: 警告: [unchecked] 对作为原始类型Map的成员的put(K,V)的调用未经过检查
		__xml_namespaceMap.put("$DEFAULT","http://wadl.dev.java.net/2009/02");
		                      ^
  其中, K,V是类型变量:
    K扩展已在接口 Map中声明的Object
    V扩展已在接口 Map中声明的Object
1 个警告

:processResources
:classes
:jar
:assemble

BUILD SUCCESSFUL in 1s
4 actionable tasks: 4 executed

**
  

result: fastrpcgen.jar is found in ~/RPC/RPC/fastrpcgen/build/libs
           rpcddsjen.jar   is not found
           rpcrestjen.jar is not found


how to install rpcddsgen tool???
 
thanks.

**Comment by Tooo-Top** [comment]
> hello:
> 
> 1. env:
>    java -version
>    java version "1.8.0_321"
>    Java(TM) SE Runtime Environment (build 1.8.0_321-b07)
>    Java HotSpot(TM) 64-Bit Server VM (build 25.321-b07, mixed mode)
> 
> gradle -v Gradle 4.4.1
> 
> 2. Steps：
>    $ mkdir ~/RPC
>    $ cd RPC
>    $ git clone https://github.com/eProsima/RPC.git
>    master branch
>    $ cd ~/RPC/RPC/fastrpcgen
>    $ gradle assemble
>    **
>    ANTXR Parser Generator   Version 0.9.0   Copyright (c) 2005, Scott Stanchfield, JavaDude.com
>    :buildIDLParser
>    :idl:clean
>    :idl:antlr4 UP-TO-DATE
>    :idl:compileJava
>    :idl:processResources
>    :idl:classes
>    :idl:jar
>    :idl:assemble
>    :idl:compileTestJava NO-SOURCE
>    :idl:processTestResources NO-SOURCE
>    :idl:testClasses UP-TO-DATE
>    :idl:test NO-SOURCE
>    :idl:check UP-TO-DATE
>    :idl:build
>    :compileJava/home/zhito/RPC/RPC/fastrpcgen/build/generated-src/com/eprosima/fastrpc/wadl/grammar/WADLParser.java:42: 警告: [unchecked] 对作为原始类型Map的成员的put(K,V)的调用未经过检查
>    __xml_namespaceMap.put("$DEFAULT","http://wadl.dev.java.net/2009/02");
>    ^
>    其中, K,V是类型变量:
>    K扩展已在接口 Map中声明的Object
>    V扩展已在接口 Map中声明的Object
>    1 个警告
>    :processResources
>    :classes
>    :jar
>    :assemble
>    BUILD SUCCESSFUL in 1s
>    4 actionable tasks: 4 executed
>    **
> 
> 3.result: fastrpcgen.jar is found in ~/RPC/RPC/fastrpcgen/build/libs rpcddsjen.jar is not found rpcrestjen.jar is not found
> 
> how to install rpcddsgen tool???
> 
> thank you.

Has the problem been solved?

**Comment by hero952** [comment]
邮件已经收到，谢谢！

**Comment by Tooo-Top** [comment]
> 邮件已经收到，谢谢！

怎么联系。也有这个问题。不知道你解决了么。

**Comment by 1514LT** [comment]
> > 邮件已经收到，谢谢！
> 
> 怎么联系。也有这个问题。不知道你解决了么。

怎么联系，解决了吗，我Linux和Windows都试了，一直报下面的错：
lt@openeuler:~/workspace/FASTDDS/RPC$ fastrpcgen -example x64Linux2.6gcc4.4.5 HelloWorld.idl
openjdk version "11.0.27" 2025-04-15
OpenJDK Runtime Environment (build 11.0.27+6-post-Ubuntu-0ubuntu120.04)
OpenJDK 64-Bit Server VM (build 11.0.27+6-post-Ubuntu-0ubuntu120.04, mixed mode, sharing)
Processing the file HelloWorld.idl ...
CDRProtocolSource.stg 123:57: invalid character '}'
CDRProtocolSource.stg 140:57: invalid character '}'
CDRProtocolSource.stg 142:53: mismatched input 'else' expecting RDELIM
CDRProtocolSource.stg 226:77: mismatched input '}' expecting LDELIM
CDRProtocolSource.stg 400:50: invalid character '}'
ERROR: Cannot generate the files
Exception in thread "main" java.lang.NullPointerException
        at com.eprosima.fastrpc.fastrpcgen.process(fastrpcgen.java:836)
        at com.eprosima.fastrpc.fastrpcgen.execute(fastrpcgen.java:677)
        at com.eprosima.fastrpc.fastrpcgen.main(fastrpcgen.java:2268)
lt@openeuler:~/workspace/FASTDDS/RPC$ rp
rpcddsgen    rpdfcrop     rpm2archive  rpmbuild     rpmgraph     rpmquery     rpmspec
rpcgen       rpm          rpm2cpio     rpmdb        rpmkeys      rpmsign      rpmverify
lt@openeuler:~/workspace/FASTDDS/RPC$ rp
rpcddsgen    rpdfcrop     rpm2archive  rpmbuild     rpmgraph     rpmquery     rpmspec
rpcgen       rpm          rpm2cpio     rpmdb        rpmkeys      rpmsign      rpmverify
lt@openeuler:~/workspace/FASTDDS/RPC$ rpc
rpcddsgen  rpcgen
lt@openeuler:~/workspace/FASTDDS/RPC$ rpcddsgen -example x64Linux2.6gcc4.4.5 HelloWorld.idl
openjdk version "11.0.27" 2025-04-15
OpenJDK Runtime Environment (build 11.0.27+6-post-Ubuntu-0ubuntu120.04)
OpenJDK 64-Bit Server VM (build 11.0.27+6-post-Ubuntu-0ubuntu120.04, mixed mode, sharing)
ERROR: Getting vendor. null
Processing the file HelloWorld.idl ...
ERROR<Exception>: no such attribute: operation_type
java.lang.IllegalArgumentException: no such attribute: operation_type
        at org.stringtemplate.v4.ST.add(ST.java:224)
        at com.eprosima.idl.generator.manager.TemplateGroup.setAttribute(TemplateGroup.java:101)
        at com.eprosima.idl.parser.grammar.IDLParser.op_decl(IDLParser.java:9788)
        at com.eprosima.idl.parser.grammar.IDLParser.export(IDLParser.java:1394)
        at com.eprosima.idl.parser.grammar.IDLParser.interface_body(IDLParser.java:1209)
        at com.eprosima.idl.parser.grammar.IDLParser.interface_decl(IDLParser.java:1049)
        at com.eprosima.idl.parser.grammar.IDLParser.interface_or_forward_decl(IDLParser.java:898)
        at com.eprosima.idl.parser.grammar.IDLParser.definition(IDLParser.java:522)
        at com.eprosima.idl.parser.grammar.IDLParser.specification(IDLParser.java:347)
        at com.eprosima.fastrpc.fastrpcgen.parseIDLtoDDS(fastrpcgen.java:1263)
        at com.eprosima.fastrpc.fastrpcgen.process(fastrpcgen.java:774)
        at com.eprosima.fastrpc.fastrpcgen.execute(fastrpcgen.java:677)
        at com.eprosima.fastrpc.rpcddsgen.main(rpcddsgen.java:27)
lt@openeuler:~/workspace/FASTDDS/RPC$

**Comment by hero952** [comment]
邮件已经收到，谢谢！
